### ISSUE TITLE
Importar CSV de Estructura Orgánica y Autoridades del PEN

### ISSUE THREAD

**Issue by martinszy** [ConocimientoAbierto/policrowd#11]
Fuente: http://datos.gob.ar/dataset/estructura-organica-pen/

**Comment by godiard** [comment]
Que buena data! Creo que está bueno importarlo, lo unico que me preocupa es que si nos ponemos a agregar tareas a algo que ya sabemos que estabamos jugados con el tiempo, vamos a terminar ahorcados.

**Comment by martinszy** [comment]
Esto lo hago yo, si necesito alguna ayuda concreta te creo otro issue, por
si hace falta algún campo o modificación.

**Comment by godiard** [comment]
Ok. Lo que tenemos que acordar es como se va a subir, asi las vistas ya despliegan esta info.

**Comment by martinszy** [comment]
No está funcionando esta importación, por favor revisar.

```

$ ./manage.py candidates_import_argentina_politicians
Traceback (most recent call last):
  File "./manage.py", line 45, in <module>
    execute_from_command_line(sys.argv)
  File "/home/poli/.virtualenvs/poli/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/poli/.virtualenvs/poli/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/poli/.virtualenvs/poli/local/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/poli/.virtualenvs/poli/local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/poli/yournextrepresentative/candidates/management/commands/candidates_import_argentina_politicians.py", line 143, in handle
    self.prepareCaches()
  File "/home/poli/yournextrepresentative/candidates/management/commands/candidates_import_argentina_politicians.py", line 28, in prepareCaches
    self.prepareExecutivePowerCache()
  File "/home/poli/yournextrepresentative/candidates/management/commands/candidates_import_argentina_politicians.py", line 20, in prepareExecutivePowerCache
    self.executivePowerCache = Organization.objects.get(name='Poder Ejecutivo')
  File "/home/poli/.virtualenvs/poli/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/poli/.virtualenvs/poli/local/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
popolo.models.DoesNotExist: Organization matching query does not exist.

```

**Comment by godiard** [comment]
Hay que agregar una organización "Poder Ejecutivo" y relacionarla con el area "Argentina".
Lo ideal sería que candidates_import_argentina_politicians.py se fijara si ya existe y si no que lo agregue. Se nota que esta organización la agregó Cristian a mano.
Si no podes hacer esto, le digo que haga la modificación en cuanto se reincorpore.

**Comment by martinszy** [comment]
Esto lo tendrían que hacer las migraciones o quizás el mismo script de management. Lo voy a revisar.

**Comment by martinszy** [comment]
Ok, modificando un par de líneas ahora corrió.

Pero tiró warnings.

```
$ ./manage.py candidates_import_argentina_politicians
Inserting Organizations...

/home/poli/.virtualenvs/poli/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:578: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if not self.blank and value in self.empty_values:

/home/poli/.virtualenvs/poli/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:535: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if value in self.empty_values:

/home/poli/.virtualenvs/poli/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Organization.created_at received a naive datetime (2016-04-11 17:22:36) while time zone support is active.
  RuntimeWarning)

/home/poli/.virtualenvs/poli/local/lib/python2.7/site-packages/django/db/models/base.py:1188: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if f.blank and raw_value in f.empty_values:

/home/poli/.virtualenvs/poli/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Post.created_at received a naive datetime (2016-04-11 17:22:36) while time zone support is active.
  RuntimeWarning)

/home/poli/.virtualenvs/poli/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Person.created_at received a naive datetime (2016-04-11 17:22:36) while time zone support is active.
  RuntimeWarning)

/home/poli/.virtualenvs/poli/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py:1474: RuntimeWarning: DateTimeField Membership.created_at received a naive datetime (2016-04-11 17:22:36) while time zone support is active.
  RuntimeWarning)


```

**Comment by martinszy** [comment]
Funciona y está hecho.
