### ISSUE TITLE
Add municipal areas

### ISSUE THREAD

**Issue by martinszy** [ConocimientoAbierto/policrowd#8]
We should add localities for the whole country.

This involves finding the shapefiles and importing them to mapit. Or using the OSM ones.

Context here: https://github.com/mysociety/yournextrepresentative/issues/532

**Comment by martinszy** [comment]
Comment from original issue:
Here's the list of areas:
http://www.ign.gob.ar/NuestasActividades/sigign#descarga
Also here you can get a list of municipalities from a different source:
https://github.com/jazzido/muniscraper

**Comment by martinszy** [comment]
Esto no está funcionando.

```
$ ./manage.py candidates_import_areas
Inserting Areas...

Traceback (most recent call last):
  File "./manage.py", line 45, in <module>
    execute_from_command_line(sys.argv)
  File "/home/poli/.virtualenvs/poli/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/poli/.virtualenvs/poli/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/poli/.virtualenvs/poli/local/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/poli/.virtualenvs/poli/local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/poli/yournextrepresentative/candidates/management/commands/candidates_import_areas.py", line 101, in handle
    self.fetchAllAreas()
  File "/home/poli/yournextrepresentative/candidates/management/commands/candidates_import_areas.py", line 72, in fetchAllAreas
    areaTypeId = self.areaTypesCache['MUN']
KeyError: 'MUN'

```

**Comment by godiard** [comment]
Aca hay que agregar un tipo de area "MUN"

**Comment by martinszy** [comment]
Esto lo tendrían que hacer las migraciones o quizás el mismo script de management. Lo voy a revisar.

**Comment by martinszy** [comment]
Modificaciones:
Linea 49
`argentinaId = Area.objects.get_or_create(name='Argentina')[0].id`

Linea 58:
`munArea = AreaType.objects.get_or_create(name="MUN")`

Nuevo error:

```
$ ./manage.py candidates_import_areas
Inserting Areas...

Traceback (most recent call last):
  File "./manage.py", line 45, in <module>
    execute_from_command_line(sys.argv)
  File "/home/poli/.virtualenvs/poli/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/poli/.virtualenvs/poli/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/poli/.virtualenvs/poli/local/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/poli/.virtualenvs/poli/local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/home/poli/yournextrepresentative/candidates/management/commands/candidates_import_areas.py", line 102, in handle
    self.fetchAllAreas()
  File "/home/poli/yournextrepresentative/candidates/management/commands/candidates_import_areas.py", line 81, in fetchAllAreas
    parentId = self.provincesAreasCache[self.areaDifferencesMap[parentAreaName]]
KeyError: 'BUENOS AIRES'

```

**Comment by cesuarez** [comment]
Acabo de hacer los cambios q hiciste vos con algunas modificaciones para que ya esté subido.

El script te está tirando ese error porque asume que las provincias ya están creadas en la Base de Datos. Si queres que el script también las agregue si no existen avisame

**Comment by martinszy** [comment]
Si, por favor, que tome el listado de un archivo externo y las cree.
Por un lado para poder replicar el entorno de servidor en caso de
reinstalación.
Y además porque todo esto tiene que poder ser instalable sin tocar la db,
con la esperanza de que un día nos dejen mergear.

**Comment by martinszy** [comment]
Funciona!
